// src/pages/auth/login.tsx
import React, { useState } from 'react';
import { useAuth } from '@/contexts/AuthContext';
import { useForm } from 'react-hook-form';
import { LoginCredentials } from '@/types/auth';
import { SecurityIcon, LockIcon } from '@/components/icons';
import { Alert } from '@/components/ui/Alert';

export default function LoginPage() {
  const { login, isLoading } = useAuth();
  const [error, setError] = useState<string | null>(null);
  const { register, handleSubmit, formState: { errors } } = useForm<LoginCredentials>();

  const onSubmit = async (data: LoginCredentials) => {
    try {
      setError(null);
      await login(data);
      // Redirect to MFA page is handled by AuthContext
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Login failed');
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 flex flex-col justify-center py-12 sm:px-6 lg:px-8">
      <div className="sm:mx-auto sm:w-full sm:max-w-md">
        <SecurityIcon className="mx-auto h-12 w-12 text-indigo-600" />
        <h2 className="mt-6 text-center text-3xl font-extrabold text-gray-900">
          Sign in to SecureAI
        </h2>
        <p className="mt-2 text-center text-sm text-gray-600">
          Secure access with mandatory two-factor authentication
        </p>
      </div>

      <div className="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
        <div className="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
          {error && (
            <Alert type="error" message={error} className="mb-4" />
          )}

          <form className="space-y-6" onSubmit={handleSubmit(onSubmit)}>
            <div>
              <label htmlFor="email" className="block text-sm font-medium text-gray-700">
                Email address
              </label>
              <div className="mt-1">
                <input
                  id="email"
                  type="email"
                  autoComplete="email"
                  required
                  className="appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                  {...register('email', {
                    required: 'Email is required',
                    pattern: {
                      value: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i,
                      message: 'Invalid email address',
                    },
                  })}
                />
                {errors.email && (
                  <p className="mt-2 text-sm text-red-600">{errors.email.message}</p>
                )}
              </div>
            </div>

            <div>
              <label htmlFor="password" className="block text-sm font-medium text-gray-700">
                Password
              </label>
              <div className="mt-1">
                <input
                  id="password"
                  type="password"
                  autoComplete="current-password"
                  required
                  className="appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                  {...register('password', {
                    required: 'Password is required',
                    minLength: {
                      value: 12,
                      message: 'Password must be at least 12 characters',
                    },
                  })}
                />
                {errors.password && (
                  <p className="mt-2 text-sm text-red-600">{errors.password.message}</p>
                )}
              </div>
            </div>

            <div className="flex items-center justify-between">
              <div className="text-sm">
                <a href="/auth/reset-password" className="font-medium text-indigo-600 hover:text-indigo-500">
                  Forgot your password?
                </a>
              </div>
            </div>

            <div>
              <button
                type="submit"
                disabled={isLoading}
                className="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 disabled:opacity-50"
              >
                {isLoading ? (
                  <span className="flex items-center">
                    <LockIcon className="animate-spin -ml-1 mr-3 h-5 w-5 text-white" />
                    Signing in...
                  </span>
                ) : (
                  'Sign in'
                )}
              </button>
            </div>
          </form>

          <div className="mt-6">
            <div className="relative">
              <div className="absolute inset-0 flex items-center">
                <div className="w-full border-t border-gray-300" />
              </div>
              <div className="relative flex justify-center text-sm">
                <span className="px-2 bg-white text-gray-500">
                  Security Notice
                </span>
              </div>
            </div>

            <div className="mt-6 text-xs text-gray-500 text-center">
              <p>This system requires two-factor authentication.</p>
              <p className="mt-1">All login attempts are monitored and logged.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// src/routes/login/+page.svelte
<script lang="ts">
  import { goto } from '$app/navigation';
  import { enhance } from '$app/forms';
  import { auth } from '../../contexts/AuthContext';
  import { invalidate } from '$app/navigation';
  import type { SubmitFunction } from '@sveltejs/kit';

  export let form;

  let email = '';
  let password = '';
  let loading = false;
  let submitting = false;

  const submit: SubmitFunction = () => {
    submitting = true;
    return async ({ update }) => {
        await update();
        submitting = false;
    };
};
  async function handleSubmit() {
    loading = true;
    error = '';
    emailError = '';
    passwordError = '';


    // Simple form validation
    if (!email) {
        emailError = 'Email is required';
    } else if (!/^[w-.]+@([w-]+.)+[w-]{2,4}$/.test(email)) {
        emailError = 'Invalid email format';
    }

    if (!password) {
        passwordError = 'Password is required';
    }

    if(emailError || passwordError){
      loading = false;
      return
    }


    const loginResult = await $auth.login(email, password);
    if (loginResult.success) {
      if ($auth.needsMFA) {
        goto('/mfa');
      } else {
        goto('/dashboard');
      }
    } else {
      error = loginResult.error || 'Login failed';
      if (Array.isArray(loginResult.error)) {
        error = loginResult.error[0].msg;
      }
    }
    loading = false;
    
    if ($auth.error) {
      error = $auth.error;
    }
  }


</script>
<svelte:head>
	<title>Login</title>
	<meta name="description" content="Login" />
</svelte:head>
<main class="flex flex-col items-center justify-center h-screen bg-gray-100">
    <div class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4 flex flex-col w-80">
        <h1 class="text-2xl font-bold mb-6 text-center">Login</h1>
        {#if form?.error}
            <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mb-4" role="alert">
                <strong class="font-bold">Error! </strong>
                <span class="block sm:inline">{form.error}</span>
            </div>
        {/if}
        <form method="POST" use:enhance={submit} on:submit|preventDefault={handleSubmit}>
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="email">
                    Email
                </label>
                <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline {form?.emailError ? 'border-red-500' : 'border-gray-300'}" id="email" type="email" placeholder="Email" bind:value={email} aria-invalid={form?.emailError ? 'true' : 'false'} aria-describedby="email-error" />
                {#if form?.emailError}
                    <p class="text-red-500 text-xs italic mt-1" id="email-error">{form.emailError}</p>
                {/if}
            </div>
            <div class="mb-6">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="password">
                    Password
                </label>
                <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline {form?.passwordError ? 'border-red-500' : 'border-gray-300'}" id="password" type="password" placeholder="Password" bind:value={password} aria-invalid={form?.passwordError ? 'true' : 'false'} aria-describedby="password-error" />
                {#if form?.passwordError}
                    <p class="text-red-500 text-xs italic mt-1" id="password-error">{form.passwordError}</p>
                {/if}
            </div>
            <div class="flex items-center justify-between">
                <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit" disabled={loading || submitting}>
                    {#if submitting}
                        Loading...
                    {:else}
                        Login
                    {/if}
                </button>
                <a class="inline-block align-baseline font-bold text-sm text-blue-500 hover:text-blue-800" href="/password-reset">
                    Forgot Password?
                </a>
            </div>
        </form>
        <div class="mt-4 text-center">
            <a class="inline-block text-sm text-blue-500 hover:text-blue-800" href="/signup">
                Don't have an account? Sign up
            </a>
        </div>
    </div>
</main>

<style global>
	/* Apply Tailwind's base styles */
	@tailwind base;
	@tailwind components;
	@tailwind utilities;
  
  .input-error{
    border-color: #dc2626;
  }
  .container {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        height: 100vh;
        background-color: #f7f7f7;
    }
    .form-group {
        margin-bottom: 1rem;
        width: 100%;
    }
  
</style>
